name: CI/CD

on: push

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script
      run: python -m unittest script_test.py

  fasta2nex:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script
      run: python3 fasta2nex.py test.fasta

  pep8:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
    - uses: actions/checkout@v2
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      run: flake8 .
